CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  description VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  slug VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE post_tags (
  post_id INT NOT NULL,
  tag_id INT NOT NULL,
  PRIMARY KEY (post_id, tag_id),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

ALTER TABLE posts
  CHANGE COLUMN cover_image featured_image VARCHAR(255) DEFAULT NULL,
  ADD COLUMN featured_image_alt VARCHAR(255) DEFAULT NULL AFTER featured_image,
  ADD COLUMN excerpt TEXT DEFAULT NULL AFTER content,
  ADD COLUMN category_id INT DEFAULT NULL AFTER excerpt,
  ADD COLUMN meta_title VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_description VARCHAR(300) DEFAULT NULL,
  ADD COLUMN status ENUM('draft', 'published', 'archived') DEFAULT 'draft' AFTER slug,
  ADD COLUMN views_count INT DEFAULT 0,
  ADD CONSTRAINT fk_posts_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;

ALTER TABLE projects
  DROP COLUMN image_url,
  DROP COLUMN link,
  ADD COLUMN subtitle VARCHAR(255) DEFAULT NULL AFTER title,
  ADD COLUMN category VARCHAR(100) DEFAULT NULL AFTER subtitle,
  ADD COLUMN client VARCHAR(150) DEFAULT NULL,
  ADD COLUMN role VARCHAR(150) DEFAULT NULL,
  ADD COLUMN project_date DATE DEFAULT NULL,
  ADD COLUMN tags VARCHAR(255) DEFAULT NULL,
  ADD COLUMN features JSON DEFAULT NULL,
  ADD COLUMN thumbnail VARCHAR(255) DEFAULT NULL,
  ADD COLUMN cover_image VARCHAR(255) DEFAULT NULL,
  ADD COLUMN live_url VARCHAR(500) DEFAULT NULL,
  ADD COLUMN gallery JSON DEFAULT NULL,
  ADD COLUMN meta_title VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_description VARCHAR(300) DEFAULT NULL,
  ADD COLUMN views_count INT DEFAULT 0,
  ADD COLUMN sort_order INT DEFAULT 0;
